## Numpy计算数组中满足条件的个数

例如：在一个非常大的数组中（一亿个数字），找出其中数字小于5000的数字数目。

### 1.使用numpy生成一亿个随机数字 

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10000,size=int(1e8))

In [4]:
arr[:10]

array([2021, 5056, 6569, 2066, 1275, 3878, 5705, 1093, 1956,   27])

In [6]:
arr.size

100000000

### 2.使用python原生语法实现 

In [7]:
pyarr = list(arr)

In [8]:
pyarr[:10]

[2021, 5056, 6569, 2066, 1275, 3878, 5705, 1093, 1956, 27]

In [10]:
len([x for x in pyarr if x>5000])

49987425

In [11]:
%timeit len([x for x in pyarr if x>5000])

16.1 s ± 1.16 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


### 3.使用numpy向量化操作实现

In [12]:
arr[arr>5000].size

49987425

In [13]:
(arr>5000)[:10]

array([False,  True,  True, False, False, False,  True, False, False,
       False])

In [15]:
arr[arr>5000][:10]

array([5056, 6569, 5705, 9016, 5123, 8307, 6861, 9002, 7427, 9703])

In [16]:
%timeit arr[arr>5000].size

706 ms ± 11.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
Compiler time: 0.31 s


### 4.对比时间

In [17]:
16.1*1000/706

22.804532577903686