## Numpy怎样给数组怎加一个维度
* 背景：
对于一维的数据输入为了形状匹配，经常需升维变成二维。

* 需要：
在不改变数据的情况下，添加数组维度；
> 原始数组：一维数组arr=[1,2,3,4] ,shape(4,),取值分别为arr[0],arr[1],arr[2],arr[3]。
> 变形数组：二维数组arr=[[1,2,3,4]],其shape(1,4),取值分别为arr[0,0],arr[0,1],arr[0,2],arr[0,3]

* 实操：
经常需要在纸上手绘数组的形状，来查看不同数组是否形状匹配，是否要升维降维

**3种方法**
* np.newaxis: 关键字，使用索引的语法给数组添加维度
* np.expand_dims(arr,axis): 方法，和np.newaxis实现一样的功能，给arr在axis位置添加维度
* np.reshape(a,newshape): 给一个维度设置为1，完成升维

In [10]:
import numpy as np
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [2]:
np.newaxis is None

True

In [3]:
np.newaxis == None

True

### 给一维向量添加一个行维度

In [17]:
arr[np.newaxis,:]

array([[0, 1, 2, 3, 4]])

In [16]:
arr[np.newaxis,:].shape

(1, 5)

### 给一维向量添加一个列维度

In [19]:
arr[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [20]:
arr[:,np.newaxis].shape

(5, 1)

## 方法二：np.expand_dims方法
实现效果和np.newaxis一样

In [21]:
arr

array([0, 1, 2, 3, 4])

In [23]:
# 给行添加一维
np.expand_dims(arr,axis=0)

array([[0, 1, 2, 3, 4]])

In [24]:
np.expand_dims(arr,axis=0).shape

(1, 5)

In [25]:
# 给列添加一维
np.expand_dims(arr,axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

## 方法三：np.reshape方法

In [27]:
# 给行添加一个维度
arr

array([0, 1, 2, 3, 4])

In [28]:
np.reshape(arr,(1,5))

array([[0, 1, 2, 3, 4]])

In [30]:
np.reshape(arr,(1,5)).shape

(1, 5)

In [31]:
np.reshape(arr,(1,-1))
np.reshape(arr,(1,-1)).shape

(1, 5)

In [33]:
np.reshape(arr,(1,-1))

array([[0, 1, 2, 3, 4]])

In [34]:
# 添加一个列的维度
np.reshape(arr,(-1,1))

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [35]:
np.reshape(arr,(-1,1)).shape

(5, 1)