## Numpy数学统计函数

In [2]:
import numpy as np

In [6]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
np.sum(arr)

66

In [8]:
#乘积,看做为一个一维数组去乘，因为有个0元素所以结果为0
np.prod(arr)

0

In [9]:
#累加
np.cumsum(arr)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [10]:
np.cumprod(arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [11]:
np.max(arr)

11

In [12]:
np.min(arr)

0

In [13]:
#np.percentile(数组，[0-100之间的某个位置])
np.percentile(arr,[25,50,75])

array([2.75, 5.5 , 8.25])

In [14]:
np.quantile(arr,[0.25,0.5,0.75])

array([2.75, 5.5 , 8.25])

In [16]:
#中位数
np.median(arr)

5.5

In [17]:
#平均值
np.mean(arr)

5.5

In [19]:
#标准差
np.std(arr)

3.452052529534663

In [20]:
#方差
np.var(arr)

11.916666666666666

In [27]:
# 加权平均数
#*arr.shape相当于参数传递， 把tuple（1，3）里面的每一个值1 3拿出来当作参数传递
print(arr.shape)
print(*arr.shape)
weights = np.random.rand(*arr.shape)
weights

(3, 4)
3 4


array([[0.14579672, 0.31032905, 0.96285454, 0.27029229],
       [0.37779701, 0.66780395, 0.67908074, 0.11153283],
       [0.84011102, 0.79556053, 0.20255966, 0.15678075]])

In [28]:
np.average(arr,weights=weights)

5.50375144532707

## 2.Numpy axis参数用途

axis=0代表行、axis=1代表列
对于：sum/mean/median等聚合函数：
* 理解1：axis=0代表把行取消，axis=1代表把列取消掉。
* 理解2：axis=0代表跨行计算每一列。

In [30]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
arr.sum(axis=0)

array([12, 15, 18, 21])

In [35]:
arr.sum(axis=1)

array([ 6, 22, 38])

In [37]:
arr.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [38]:
arr.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

## 数据标准化
* 机器学习、神经网络中，不同列的量纲应该相同，训练收敛更快
> * 比如商品中价格0-100（行），销量1w-10w（列），这两个数字完全没有可比性，因此需要先标准化
> * 标准化：A = （A - mean（A,axis=0））/std(A,axis=0)

In [39]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
mean = np.mean(arr,axis=0)
mean

array([4., 5., 6., 7.])

In [42]:
std = np.std(arr,axis=0)
std

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [45]:
#计算分子,每一行都会减去mean,(Numpy的广播)
f = arr - mean
f

array([[-4., -4., -4., -4.],
       [ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.]])

In [46]:
result = f/std
result

array([[-1.22474487, -1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487,  1.22474487]])

**使用随机数字尝试**

In [49]:
arr = np.random.randint(1,100,size=(3,4))
arr

array([[54, 20, 31, 91],
       [98, 63, 81, 75],
       [73,  7, 93, 75]])

In [50]:
result = (arr - np.mean(arr,axis=0))/np.std(arr,axis=0)
result

array([[-1.16546824, -0.41787756, -1.39047313,  1.41421356],
       [ 1.27646522,  1.37899594,  0.47176767, -0.70710678],
       [-0.11099698, -0.96111838,  0.91870546, -0.70710678]])