## Numpy核心array对象以及创建array的方法

### array对象的背景
* Numpy的核心数据结构，叫做array数组，array对象可以是一维数组，也可以是多维数组
* Numpy array和python list的区别：
> * array的元素只能是一种数据类型，例如int型。这也是array性能比list好的一个原因。
> * array 比 list 的优点：性能更好、包含数组元数据信息、大量的便捷函数。

### array的属性
* shape : 返回一个元组，表示array的维度
* ndim ：表示array维度的数目
* size ：表示array中所有数据元素的数目
* dtype ：array中元素的数据类型

### 创建array的方法
* 从Python的列表list和嵌套列表创建array
* 使用预定函数：arange、ones/ones_like、zeros/zeros_like、empty/empty_like、full/full_like、eye等创建array
* 生成随机的数的np.random模块构建

### array支持的函数
* 直接组元素加减乘除
* 更好用的面向多维的数组索引
* 求sum/mean等聚合函数
* 线性代数函数：求解逆矩阵，求解方程组。

### 1.使用list方法创建array

In [2]:
import numpy as np

In [3]:
# 创建一个一维数组
x = np.array([1,2,3,4,5,6,7,8])

In [4]:
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
# 创建一个二维数组
X = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

In [6]:
X

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 2.数组array的属性

In [7]:
x.shape

(8,)

In [8]:
X.shape

(2, 4)

In [9]:
x.ndim

1

In [10]:
X.ndim

2

In [11]:
x.size

8

In [12]:
X.size

8

In [13]:
x.dtype

dtype('int32')

In [14]:
X.dtype

dtype('int32')

### 3.创建array的便捷函数

#### 使用arange创建数字序列
arange([star], [stop], [step], dtype=None)

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(2,10,2)

array([2, 4, 6, 8])

#### 使用ones创建全是1的数组
np.ones(shape,dtype=None,order='C')
shape:int or tuple of ints.(2,3) or 10.

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 使用ones_like创建
np.ones_like(array a,dtype=float,order='C')

In [19]:
np.ones_like(x)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
np.ones_like(X)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

### zeros和zeros_like语法和ones和ones_like一样

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros_like(x)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.zeros_like(X)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

#### 使用empty创建全是0的数组
empty(shape,dtype=float,order='C')
注意：数据是未初始化的，里面的值可能是随机值不要使用

In [24]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

#### 使用empty_like创建形状相同的数组
np.empty_like(prototype,dtype=None)

In [26]:
np.empty_like(x)

array([      0,       1,       0, 2781696,     816,       0,     768,
         32767])

In [27]:
np.empty_like(X)

array([[         0,          1,          0, 1953265005],
       [      1120,          0,        768,        163]])

#### 使用full创建指定值的数组
np.full(shape,fill_value,dtype=None,order='C')

In [28]:
np.full(10,666)

array([666, 666, 666, 666, 666, 666, 666, 666, 666, 666])

In [29]:
np.full((2,4),333)

array([[333, 333, 333, 333],
       [333, 333, 333, 333]])

#### 使用full_like创建形状相同的数组
np.full_like(a,fill_value,dtype=None)

In [30]:
np.full_like(x,666)

array([666, 666, 666, 666, 666, 666, 666, 666])

In [31]:
np.full_like(X,333)

array([[333, 333, 333, 333],
       [333, 333, 333, 333]])

#### 使用randn生成随机数组
randn(d1,d2,...,dn)

In [32]:
np.random.randn(1,2,4)

array([[[ 0.02539989, -1.99328481,  0.3288571 ,  0.72950621],
        [ 0.38075687,  0.79751698,  0.91077372,  1.11903063]]])

In [33]:
np.random.randn()

0.6491936776998002

In [34]:
np.random.randn(3,4)

array([[ 0.58743923,  0.29679865,  0.06805849,  0.15281376],
       [-0.09342628, -0.03955658,  0.43982484,  1.55144419],
       [-1.39306472,  0.12131255, -0.10240202,  1.14344059]])

#### array本身支持的大量操作和函数

In [38]:
A = np.arange(10).reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
np.arange(10).reshape(2,4)

ValueError: cannot reshape array of size 10 into shape (2,4)

In [39]:
A.shape()

TypeError: 'tuple' object is not callable

In [40]:
A.shape

(2, 5)

In [41]:
A+1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [42]:
A*3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [43]:
np.sin(A)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [44]:
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [45]:
B = np.random.randn(2,5)

In [46]:
B

array([[-0.68780673,  0.80560901,  1.30018775,  0.64735419,  0.60642389],
       [-0.83973646, -0.60214033,  0.17181034,  0.34551776, -0.73666503]])

In [47]:
A+B

array([[-0.68780673,  1.80560901,  3.30018775,  3.64735419,  4.60642389],
       [ 4.16026354,  5.39785967,  7.17181034,  8.34551776,  8.26333497]])

In [48]:
A-B

array([[0.68780673, 0.19439099, 0.69981225, 2.35264581, 3.39357611],
       [5.83973646, 6.60214033, 6.82818966, 7.65448224, 9.73666503]])